name: TestRequest
on:
  pull_request:
    branches: [develop]

jobs:
  auto-testing:
    name: Test Request For Staging
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: getdate
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d")"

      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache dependencies node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm #${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-nodecachekey-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-nodecachekey-

      - run: npm ci

      - run: npm run format:check

      - run: npm run test -- --coverage
        env:
          CI: true

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage

      - name: Send a Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # The WEBHOOK is already config to channel z_general
          #SLACK_MESSAGE: 'Deployed to Production'
          #SLACK_MESSAGE: 'New Release ${{ github.event.release.tag_name }} is published, < ${{ github.event.release.html_url }}|check it out now.>'

          SLACK_MESSAGE: ${{ steps.getdate.outputs.today }} Pull request for deployment to Staging Server has passed all CI tests and now pending merge...
          #SLACK_CHANNEL: "z_general"

      - name: Create an issue
        if: failure() && github.event_name == 'pull_request'
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{ steps.getdate.outputs.today }} Failed tests in pull request to merge to deploy.
          body: |
            ## Waiting for workflow to develop branch merge approval

            - [ ] Go over test results & comments
            - [ ] Approve (or Reject) the merge
          labels: |
            merge
            staging
